// campusData.js

export const campusDetails = [
  {
    id: 1,
    name: "Main Campus ",
    phone: "051-5680007",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 2,
    name: "Blue Birds Campus",
    phone: "+92 312 0460123",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 3,
    name: "Roomi Campus",
    phone: "051-560009",
    // location: "",
    // mapUrl: "",
  },
  {
    id: 4,
    name: "Luqman Campus",
    location: "Ninja Street Muslim Abad Rwp",
    phone: "051-560008",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 5,
    name: "The Leaders Campus",
    location: "Izzat Abad Main Girja Road ",
    phone: "051-5681888",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 6,
    name: "Paradise Campus",
    location: "Baraf Khana Chowk Rwp",
    phone: "051-5680006",
    mapUrl: "https://www.google.com/maps/...",
  },

  // 7-36 updated ↓↓

  {
    id: 7,
    name: "Siddique Campus",
    location: "Main Girja Road Rwp",
    phone: "+92 315 2780454",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 8,
    name: "Al Farooq Campus",
    location: "Main Dhoke Hassu Rwp",
    phone: "+92 315 5491257",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 9,
    name: "Al- Ghani Campus",
    location: "Dhoke Mustaqeem Rwp",
    phone: "+92 304 8979726",
    // mapUrl: "",
  },
  {
    id: 10,
    name: "Haider Campus",
    location: "Arshi Masjid Satellite Town",
    phone: "+92 310 5786008",
    // mapUrl: "",
  },
  {
    id: 11,
    name: "Ak Mustafa Campus",
    location: "Madina Colony Misrial Road Rawalpindi",
    phone: "+92 313 7737057",
    // mapUrl: "",
  },
  {
    id: 12,
    name: "Victoria Campus",
    location: "Harley Street,Rawalpindi",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 13,
    name: "High Aims Campus",
    location: "96- Harley Street Lane No 2 Rawalpindi",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 14,
    name: "Sunshine Campus",
    location: "Chakri road , Rawalpindi",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 15,
    name: "Al-Rehman Campus",
    location: "Qureshi Abad Rawalpindi",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 16,
    name: "Pioneers Campus",
    location: "Near Khanna Bridge ,Rwp",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 17,
    name: "The Rose Campus",
    location: "Near Sazuki Stop Near Chakra ,Rwp",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 18,
    name: "Faith Campus",
    location: "Thandi Sarak G.T Road Mandrah Rwp",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 19,
    name: "Iqbal Campus",
    location: "Maskeen Abad Chak Jalal Din ,Rwp",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 20,
    name: "Jinnah Campus",
    location: "Near Govt.Boys High School Dhamial , Rwp",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 21,
    name: "Sublime Campus",
    location: "Officers Colony Lane-1 Misrial Road, Rwp",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 22,
    name: "JF Campus",
    location: "Main Range Road Opp. Noor Jahan Plaza ",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 23,
    name: "Obaid-e-Raza Campus",
    location: "Iqbal Market Lane No 3 Rwp",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 24,
    name: "DHA Campus",
    location: "Adj. Gate No 1,DHA-II G.T.Road ,Islamabad",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 25,
    name: "AFAQ Campus",
    location: "Miskeen Abad, Misrial Road Rwp",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 26,
    name: "Haider Campus",
    // location: "",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 27,
    name: "Gulburg Campus",
    location: "Bismillah Abad",
    phone: "+92 313 0510052",
    // mapUrl: "",
  },
  {
    id: 28,
    name: "Ahmad Campus",
    location: "Gujranwala",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 29,
    name: "Al-Rafay Campus",
    location: "Shah Jeewan Colony Girja Road Rwp",
    mapUrl: "https://www.google.com/maps/...",
  },
  {
    id: 30,
    name: "Jinnah Campus",
    location: "Kalyal",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 31,
    name: "Zia-e-Islam Campus",
    location: "Gujranwala",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 32,
    name: "Sasardar Campus",
    location: "Gujranwala",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 33,
    name: "Gulraiz Campus",
    location: "Phase 6 Sir Syed Avenue Gulraiz Housing",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 34,
    name: "Yaqoob Campus",
    location: "Village 14 one L Tesil Renala Kurd Distic Okara",
    // phone: "",
    // mapUrl: "",
  },
  {
    id: 35,
    name: "JANS Campus",
    location: "Akbar Chowk Girja Rwp",
    phone: "+92 344 0545141",
    // mapUrl: "",
  },
];
